version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: docker/BackendDockerfile
    container_name: docker-django-vue-backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  vue:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: docker-django-vue-frontend
    command: bash -c "npm run serve"
#    volumes:
#      - .:/app
    ports:
      - "8080:8080"
